name: C++ CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
   runs-on: ${{ matrix.os }}
   strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
       compiler: ['gcc', 'clang', 'msvc']
   steps:
   - uses: actions/checkout@v2

   - name: Install dependencies
     run: |
       if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
         choco install cmake
       else
         sudo apt-get install -y cmake
       fi

   - name: Configure with CMake
     run: cmake -B build -S .

   - name: Build with CMake
     run: cmake --build build

   - name: Run tests
     run: ctest --test-dir build
